name: Sync to connectome (private)

on:
  push:
    branches:
      - main

jobs:
  sync-to-private:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI-SYNC]')"

    steps:
      # Шаг 1: Скачиваем репозиторий-назначение (connectome)
      - name: Checkout Destination Repo (connectome)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/connectome
          token: ${{ secrets.PAT_SYNC }}
          fetch-depth: 1 # <-- ВОТ ОПТИМИЗАЦИЯ. Качаем без истории.

      # Шаг 2: Скачиваем репозиторий-источник (EnMaTeS-Nest) во временную папку
      - name: Checkout Source Repo (EnMaTeS-Nest)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/EnMaTeS-Nest
          path: source-repo-temp

      # Шаг 3: Синхронизируем файлы из временной папки в целевую
      - name: Sync files from source to destination
        run: |
          mkdir -p ./02_Systems/0221_EnMaTeS/
          rsync -av --delete --exclude='.github' ./source-repo-temp/ ./02_Systems/0221_EnMaTeS/

      # Шаг 4: Коммитим и пушим изменения в connectome
      - name: Commit and push changes to connectome
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet; then
            git add -A
            git commit -m "sync: Update from EnMaTeS-Nest [CI-SYNC-BACK]"
            git push
          else
            echo "No changes to sync."
          fi