name: Sync to v01 (Client)

on:
  push:
    branches:
      - main

jobs:
  sync-to-client-v01:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Repo (EnMaTeS-Nest)
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Checkout Destination Repo (v01)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/v01
          token: ${{ secrets.PAT_SYNC_V01 }}
          path: dest-repo
          fetch-depth: 1 

      - name: Sync files to v01 subdirectory
        run: |
          mkdir -p ./dest-repo/EnMaTeS/
          rsync -av --delete --exclude='.github' ./source-repo/ ./dest-repo/EnMaTeS/

      - name: Commit and push changes to v01
        working-directory: ./dest-repo
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "sync: Receive update from EnMaTeS-Nest"
            git push
          else
            echo "No changes to sync."
          fi