name: Sync to connectome (private)

on:
  push:
    branches:
      - main

jobs:
  sync-to-private:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI-SYNC]')"

    steps:
      - name: Checkout Source Repo (EnMaTeS-Nest)
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Checkout Destination Repo (connectome)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/connectome
          token: ${{ secrets.PAT_SYNC }}
          path: dest-repo
          fetch-depth: 1

      - name: Sync files to connectome subdirectory
        run: |
          mkdir -p ./dest-repo/02_Systems/0221_EnMaTeS/
          rsync -av --delete --exclude='.github' ./source-repo/ ./dest-repo/02_Systems/0221_EnMaTeS/

      - name: Commit and push changes to connectome
        working-directory: ./dest-repo
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "sync: Update from EnMaTeS-Nest [CI-SYNC-BACK]"
            git push
          else
            echo "No changes to sync."
          fi